# Stackage resolver
resolver: lts-11.13

# Package list
packages:
- .

# Extra dependencies
extra-deps: []

# Nix integration
nix:
    packages:
    - gmp5.static
    - zlib.static
    - glibc.static
